

import 'dart:convert';
import 'package:flutter/services.dart' show rootBundle;

/// Centralized contract addresses + endpoints for the JERT network.
/// Addresses are loaded from `assets/config/contract-addresses.json`
/// which is auto-generated by Hardhat `deploy-all.ts`.
class ContractConfig {
  static late final String jertToken;
  static late final String treasuryMultisig;
  static late final String kycRegistry;
  static late final String complianceGateway;
  static late final String leaseContract;

  static late final String rpcUrl;
  static late final String apiUrl;

  static bool _initialized = false;

  /// Should be called once on app startup (e.g. in main()).
  static Future<void> load() async {
    if (_initialized) return;

    // 1) Load addresses from JSON (shared with React / docs)
    final jsonString = await rootBundle
        .loadString('assets/config/contract-addresses.json');
    final data = json.decode(jsonString) as Map<String, dynamic>;

    jertToken = data['JERTToken'] as String;
    treasuryMultisig = data['TreasuryMultisig'] as String;
    kycRegistry = data['KYCRegistry'] as String;
    complianceGateway = data['ComplianceGateway'] as String;
    leaseContract = data['LeaseContract'] as String;

    // 2) Load RPC / API endpoints from compile-time env (flutter run --dart-define=...)
    rpcUrl = const String.fromEnvironment(
      'FLUTTER_JERT_RPC_URL',
      defaultValue: 'http://127.0.0.1:8545',
    );

    apiUrl = const String.fromEnvironment(
      'FLUTTER_API_URL',
      defaultValue: 'http://localhost:3001',
    );

    _initialized = true;
  }
}
